package com.truecolours.backend.init;

import com.truecolours.backend.entity.Question;
import com.truecolours.backend.repository.QuestionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class QuestionsDatabaseLoader implements CommandLineRunner {

    @Autowired
    private QuestionRepository questionRepository;

    private final String[] questions = {
        "Who do you trust with your deepest secrets?",
        "If you needed advice on fashion, who would you go to?",
        "Who would you call for a late-night adventure?",
        "Who can make the best first impression?",
        "Who do you think would win in a dance-off?",
        "If you needed a wingman/wingwoman, who would you choose?",
        "Who would you want to be your partner in a cooking competition?",
        "Who could survive in the wilderness the longest?",
        "Who is most likely to become a famous actor/actress?",
        "Who would throw the wildest party?",
        "Who is most likely to start a successful business?",
        "Who has the best taste in music?",
        "Who could talk their way out of any situation?",
        "Who has the most interesting stories to tell?",
        "Who could charm their way into getting anything they want?",
        "Who would you trust to plan a surprise party for you?",
        "Who would you want as your teammate in a trivia contest?",
        "Who is most likely to become a millionaire?",
        "Who would you want to go on a road trip with?",
        "Who is the most adventurous?",
        "Who would you trust to take care of your pets?",
        "Who gives the best advice on relationships?",
        "Who is most likely to become a famous musician?",
        "Who could survive a zombie apocalypse?",
        "Who would you want to be your partner in a dance competition?",
        "Who is most likely to become a famous artist?",
        "Who is the most creative?",
        "Who would you trust to plan a surprise vacation for you?",
        "Who has the best sense of style?",
        "Who could talk their way into getting you a VIP pass?",
        "Who would you want to be your partner in a karaoke contest?",
        "Who is most likely to become a famous writer?",
        "Who has the most contagious laughter?",
        "Who would you trust to plan your wedding?",
        "Who is the most reliable in a crisis?",
        "Who could give the best motivational speech?",
        "Who has the most interesting hobbies?",
        "Who would you want as your partner in an escape room challenge?",
        "Who is most likely to become a famous chef?",
        "Who is the most resourceful?",
        "Who would you trust to plan your dream vacation?",
        "Who has the best taste in movies?",
        "Who could convince anyone to join their cause?",
        "Who is the most knowledgeable about pop culture?",
        "Who would you want as your partner in a cooking class?",
        "Who is most likely to become a famous athlete?",
        "Who has the best storytelling abilities?",
        "Who could win a debate on any topic?",
        "Who is the most tech-savvy?",
        "Who would you trust to plan a surprise date for you?",
        "Who is the most likely to survive on a deserted island?",
        "Who would you trust to plan a surprise party for a friend?",
        "If you needed legal advice, who would you call first?",
        "Who could make the best homemade pizza?",
        "Who is most likely to become a world traveler?",
        "Who would you want to be your partner in a dance-off against professionals?",
        "Who would you trust to organize a charity event?",
        "Who is the most skilled at DIY projects?",
        "Who has the best sense of direction?",
        "Who could throw the most epic themed party?",
        "Who is most likely to become a famous comedian?",
        "Who would you want as your partner in a cooking competition on TV?",
        "Who has the greenest thumb when it comes to gardening?",
        "Who could win a competitive eating contest?",
        "Who is the most likely to survive a horror movie scenario?",
        "Who would you trust to plan a surprise vacation for a group?",
        "Who has the best taste in interior design?",
        "Who could win a national spelling bee?",
        "Who is most likely to become a successful entrepreneur?",
        "Who would you want as your partner in a rock climbing competition?",
        "Who is the most knowledgeable about ancient history?",
        "Who could win a hot dog eating contest?",
        "Who would you trust to plan a surprise date for a friend?",
        "Who has the most impressive collection of something unusual?",
        "Who is most likely to become a famous scientist?",
        "Who would you want as your partner in a skydiving tandem?",
        "Who could win a limbo dancing competition?",
        "Who is the most likely to survive in the wild?",
        "Who would you trust to plan a surprise proposal?",
        "Who has the best sense of humor when it comes to memes?",
        "Who could win a competitive pancake flipping contest?",
        "Who is most likely to become a famous explorer?",
        "Who would you want as your partner in a salsa dancing competition?",
        "Who is the most knowledgeable about space and astronomy?",
        "Who could win a national chess tournament?",
        "Who would you trust to plan a surprise baby shower?",
        "Who has the best skills at assembling IKEA furniture?",
        "Who is most likely to become a famous fashion designer?",
        "Who would you want as your partner in a stand-up comedy act?",
        "Who is the most likely to survive a zombie apocalypse in a city?",
        "Who could win a hula hooping contest?",
        "Who would you trust to plan a surprise graduation party?",
        "Who has the best eye for photography?",
        "Who is most likely to become a famous philosopher?",
        "Who would you want as your partner in a competitive video gaming tournament?",
        "Who is the most knowledgeable about different cultures around the world?",
        "Who could win a national Rubik's Cube solving competition?",
        "Who would you trust to plan a surprise retirement party?",
        "Who has the best taste in vintage fashion?",
        "Who is most likely to become a famous environmental activist?",
        "Who is most likely to become a famous inventor?",
        "Who would you trust to plan a surprise anniversary celebration?",
        "If you needed a tour guide in a foreign city, who would you ask?",
        "Who could create the most viral TikTok dance?",
        "Who is the best at keeping secrets?",
        "Who would you want as your partner in a talent show?",
        "Who could throw the most extravagant New Year's Eve party?",
        "Who is most likely to become a famous astronaut?",
        "Who would you trust to pick the perfect gift for someone?",
        "If you needed a life coach, who would you hire?",
        "Who could win a competitive cupcake baking contest?",
        "Who has the best fashion sense for formal events?",
        "Who would you want as your partner in a stand-up paddleboarding race?",
        "Who is most likely to become a famous motivational speaker?",
        "Who could win a national spelling bee for obscure words?",
        "Who would you trust to plan a surprise baby gender reveal?",
        "If you needed advice on investing, who would you turn to?",
        "Who could create the most impressive sandcastle on the beach?",
        "Who is most likely to become a famous archaeologist?",
        "Who would you want as your partner in a synchronized swimming competition?",
        "Who has the best sense of direction in unfamiliar places?",
        "Who could win a competitive cooking show like MasterChef?",
        "Who would you trust to plan a surprise graduation party for your sibling?",
        "If you needed help with a car repair, who would you call first?",
        "Who could win a national Rubik's Cube solving competition?",
        "Who is most likely to become a famous wildlife conservationist?",
        "Who would you want as your partner in a duet singing competition?",
        "Who has the best eye for spotting rare birds in nature?",
        "Who could create the most realistic portrait with oil paints?",
        "Who would you trust to plan a surprise retirement party for a colleague?",
        "If you needed advice on starting a garden, who would you consult?",
        "Who could win a competitive Mario Kart race?",
        "Who is most likely to become a famous marine biologist?",
        "Who would you want as your partner in a three-legged race?",
        "Who has the best knack for finding hidden treasures in thrift stores?",
        "Who could win a national geography bee?",
        "Who would you trust to plan a surprise vow renewal ceremony?",
        "If you needed a workout buddy, who would you choose?",
        "Who could create the most elaborate origami sculpture?",
        "Who is most likely to become a famous space explorer?",
        "Who would you want as your partner in a synchronized ice skating routine?",
        "Who has the best taste in selecting books for a book club?",
        "Who could win a competitive chess match?",
        "Who would you trust to plan a surprise pet adoption event?",
        "If you needed advice on adopting a healthier lifestyle, who would you seek?",
        "Who is most likely to become a famous wildlife photographer?",
        "Who would you want as your partner in a competitive puzzle-solving contest?",
        "Who has the best taste in picking out fine wines?",
        "Who could create the most stunning flower arrangement?",
        "Who is most likely to become a famous advocate for mental health?"
    };


    @Override
    public void run(String... args) throws Exception {
        if (questionRepository.count() == 0) {
            for (String questionStr: questions) {
                Question question = new Question();
                question.setQuestion(questionStr);
                questionRepository.save(question);
            }
        }
    }
}


