import { ColorModeScript } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import theme from "./styles/theme";
import { ColorModeSwitcher } from './components/ColorModeSwitcher'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ColorModeScript initialColorMode={theme.config.initialColorMode}/>
        <Providers>
          <ColorModeSwitcher/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
