INSERT INTO question (id, question) VALUES
(1, 'Who is the best dancer?'),
(2, 'Who is the most adventurous?'),
(3, 'Who is the most likely to become a millionaire?'),
(4, 'Who would make the best detective?'),
(5, 'Who is the most likely to survive a zombie apocalypse?'),
(6, 'Who has the most unusual hobby?'),
(7, 'Who is the biggest foodie?'),
(8, 'Who is the most likely to start a dance party in public?'),
(9, 'Who is the most tech-savvy?'),
(10, 'Who is the most likely to become a famous actor/actress?'),
(11, 'Who is the most creative thinker?'),
(12, 'Who has the most impressive book collection?'),
(13, 'Who would win in a karaoke contest?'),
(14, 'Who is the most likely to become a world traveler?'),
(15, 'Who is the most knowledgeable about pop culture?'),
(16, 'Who would be the best stand-up comedian?'),
(17, 'Who is the most likely to survive in the wilderness?'),
(18, 'Who is the best at keeping secrets?'),
(19, 'Who is the most stylish?'),
(20, 'Who would make the best superhero?');