# fly.toml app configuration file generated for true-colours-backend on 2023-10-12T21:32:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "true-colours-backend"
primary_region = "sin"

[build]
  image = "ghcr.io/ebilsanta/true-colours-backend:latest"

[http_service]
  internal_port = 8080
  # force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
