# fly.toml app configuration file generated for true-colours-backend on 2023-10-28T14:35:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "true-colours-backend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
